##
# This code piece is not being used anywhere as of now.

CSEI:
  ros_parameters:
    M: [16.11, 0, 0, 0, 24.11, 0.5291, 0, 0.5291, 2.7600]           # Inertia matrix
    Xd: [-0.655, 0.3545, -3.787, 0, -2.443, 0, 0, 0, 0]             # Damping coefficients in surge
    Yd: [-1.33, -2.776, -64.91, -2.8, -3.450, 0, -0.805, -0.845, 0] # Damping coefficients in sway
    Zd: [0, -0.2088, 0, -1.90, -0.75, 0, 0.130, 0.080, 0]           # Damping coefficients in yaw
    A:  [-2.0, 0, 0, 0, -10.0, 0, 0, 0, -1.0]                       # Added Mass matrix
    m: 14.11                                                        # Rigid body mass
    Iz: 1.760                                                       # Inertial moment
    xg: 0.0375                                                      # Center of gravity

    ### Student parameters go here
    eta0: [0, 0, 0]                                   # Initial position of vessel
    dt: 0.01                                          # Timestep used for numerical integration
    ### End of student code ###
