# This file is part of TMR4243 Lecture Material.
#
# TMR4243 Lecture Material software is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TMR4243 Lecture Material software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# CyberShip Enterpries Suite. If not, see <https://www.gnu.org/licenses/>.
#
# Maintainer: Emir Cem Gezer
# Email: emir.cem.gezer@ntnu.no, emircem.gezer@gmail.com
# Year: 2022
# Copyright (C) 2024 NTNU Marine Cybernetics Laboratory

float64[] eta_d
float64[] eta_ds
float64[] eta_ds2
float64 w
float64 v_s
float64 v_ss